In [1]:
import pandas as pd

In [3]:
df = pd.read_csv(r'C:\Users\gaurk\Desktop\Herogazm\Task-01-10-26\Students_messy.csv')

In [4]:
df

,Name,Age,Gender,City,Maths,Physics,Attendance,Email
0,Akshat Aneja,22.0,Male,Hyderabad,85,78.0,92,akshat@email.com
1,Rahul Sharma,21.0,male,mumbai,72,81.0,88,rahul@email.com
2,PRIYA MEHTA,23.0,Female,Delhi,91,95.0,97,priya@email.com
3,Arjun Kumar,22.0,Male,Hyderabad,68,74.0,81,arjun@email.com
4,Neha Singh,NaN,female,Mumbai,95,89.0,94,neha@email.com
5,Rohan Das,20.0,Male,Delhi,64,NaN,76,rohan@email.com
6,Sneha Patel,21.0,FEMALE,Pune,88,92.0,105,sneha@email.com
7,Vikram Rao,150.0,Male,Hyderabad,76,71.0,85,vikram@email.com
8,Aman Verma,22.0,Male,Delhi,82,79.0,90,NaN
9,Akshat Aneja,22.0,Male,Hyderabad,85,78.0,92,akshat@email.com
10,Karan Shah,19.0,Male,NaN,73,68.0,79,karan@email.com
11,Meera Joshi,24.0,Female,Pune,89,93.0,-10,meera@email.com

In [10]:
print("Shape: ", df.shape)
print("Columns:", df.columns.tolist())
print("Data Types:\n", df.dtypes)

Shape:  (12, 8)
Columns: ['Name', 'Age', 'Gender', 'City', 'Maths', 'Physics', 'Attendance', 'Email']
Data Types:
 Name           object
Age           float64
Gender         object
City           object
Maths           int64
Physics       float64
Attendance      int64
Email          object
dtype: object

In [11]:
# checking missing values
df.isnull().sum()

Name          0
Age           1
Gender        0
City          1
Maths         0
Physics       1
Attendance    0
Email         1
dtype: int64

In [18]:
print(df.duplicated().sum())
df[df.duplicated()]

1

,Name,Age,Gender,City,Maths,Physics,Attendance,Email
9,Akshat Aneja,22.0,Male,Hyderabad,85,78.0,92,akshat@email.com

#### Removing dublicates

In [19]:
df = df.drop_duplicates()

In [22]:
df.duplicated().sum()

np.int64(0)

In [39]:
print(df['Gender'].unique())
print(df["City"].unique())

['Male' 'Female']
['Hyderabad' 'Mumbai' 'Delhi' 'Pune' nan]

#### Removing extra spaces

In [31]:
df["Name"] = df["Name"].str.strip()
df["Gender"] = df["Gender"].str.strip()
df["City"] = df["City"].str.strip()
df["Email"] = df["Email"].str.strip()

C:\Users\gaurk\AppData\Local\Temp\ipykernel_31780\561900279.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Name"] = df["Name"].str.strip()
C:\Users\gaurk\AppData\Local\Temp\ipykernel_31780\561900279.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Gender"] = df["Gender"].str.strip()
C:\Users\gaurk\AppData\Local\Temp\ipykernel_31780\561900279.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["City"] = df["City"].str.strip()
C:\Users\gaurk\AppData\Local\Temp\ipykernel_31780\561900279.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Email"] = df["Email"].str.strip()

#### Captitalization

In [32]:
df['Gender']= df['Gender'].str.title()
df['City'] = df['City'].str.title()

C:\Users\gaurk\AppData\Local\Temp\ipykernel_31780\2696281319.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Gender']= df['Gender'].str.title()
C:\Users\gaurk\AppData\Local\Temp\ipykernel_31780\2696281319.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['City'] = df['City'].str.title()

In [40]:
print(df['Gender'].unique())
print(df['City'].unique())

['Male' 'Female']
['Hyderabad' 'Mumbai' 'Delhi' 'Pune' nan]

In [42]:
df[["Name", "Gender", "City", "Email"]]

            Name  Gender       City             Email
0   Akshat Aneja    Male  Hyderabad  akshat@email.com
1   Rahul Sharma    Male     Mumbai   rahul@email.com
2    PRIYA MEHTA  Female      Delhi   priya@email.com
3    Arjun Kumar    Male  Hyderabad   arjun@email.com
4     Neha Singh  Female     Mumbai    neha@email.com
5      Rohan Das    Male      Delhi   rohan@email.com
6    Sneha Patel  Female       Pune   sneha@email.com
7     Vikram Rao    Male  Hyderabad  vikram@email.com
8     Aman Verma    Male      Delhi               NaN
10    Karan Shah    Male        NaN   karan@email.com
11   Meera Joshi  Female       Pune   meera@email.com

In [41]:
df.isnull().sum()

Name          0
Age           1
Gender        0
City          1
Maths         0
Physics       1
Attendance    0
Email         1
dtype: int64

#### Handling missing Age

In [45]:
age = df["Age"].median()
print(age)

22.0

In [46]:
df['Age'] = df['Age'].fillna(age)

C:\Users\gaurk\AppData\Local\Temp\ipykernel_31780\3460789874.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Age'] = df['Age'].fillna(age)

In [48]:
df['Age'].isnull().sum()

np.int64(0)

#### Handling Missing Physics

In [49]:
phys = df['Physics'].median()
print(phys)

80.0

In [50]:
df['Physics'] =df['Physics'].fillna(phys)

C:\Users\gaurk\AppData\Local\Temp\ipykernel_31780\2974072264.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Physics'] =df['Physics'].fillna(phys)

In [51]:
df['Physics'].isnull().sum()

np.int64(0)

#### Handling missing City using "Unknown"

In [52]:
df["City"] = df["City"].fillna("Unknown")

C:\Users\gaurk\AppData\Local\Temp\ipykernel_31780\2332208050.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["City"] = df["City"].fillna("Unknown")

In [53]:
df["City"].isnull().sum()

np.int64(0)

#### Handle missing Email

In [54]:
df["Email"] = df["Email"].fillna("Unknown")

C:\Users\gaurk\AppData\Local\Temp\ipykernel_31780\1064174939.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Email"] = df["Email"].fillna("Unknown")

In [55]:
df["Email"].isnull().sum()

np.int64(0)

In [56]:
df.isnull().sum()

Name          0
Age           0
Gender        0
City          0
Maths         0
Physics       0
Attendance    0
Email         0
dtype: int64

#### Checking and Handling Invalid values

In [57]:
df[["Age", "Maths", "Physics", "Attendance"]]

      Age  Maths  Physics  Attendance
0    22.0     85     78.0          92
1    21.0     72     81.0          88
2    23.0     91     95.0          97
3    22.0     68     74.0          81
4    22.0     95     89.0          94
5    20.0     64     80.0          76
6    21.0     88     92.0         105
7   150.0     76     71.0          85
8    22.0     82     79.0          90
10   19.0     73     68.0          79
11   24.0     89     93.0         -10

##### Set valid ranges
Age should be between 15 and 100 

Maths should be between 0 and 100

Physics should be between 0 and 100

Attendance should be between 0 and 100

##### Find Invalid Age

In [70]:
df.loc[~df['Age'].between(15,100), 'Age']

7    150.0
Name: Age, dtype: float64

In [71]:
df.loc[~df['Age'].between(15,100), 'Age'] = pd.NA

In [72]:
df["Age"].isnull().sum()

np.int64(1)

In [73]:
df["Age"] = df["Age"].fillna(df["Age"].median())

C:\Users\gaurk\AppData\Local\Temp\ipykernel_31780\2130911433.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Age"] = df["Age"].fillna(df["Age"].median())

In [75]:
df["Age"].isnull().sum()
df['Age']

0     22.0
1     21.0
2     23.0
3     22.0
4     22.0
5     20.0
6     21.0
7     22.0
8     22.0
10    19.0
11    24.0
Name: Age, dtype: float64

##### Find invalid Attendance

In [77]:
df.loc[~df["Attendance"].between(0, 100), "Attendance"] = pd.NA

In [78]:
df["Attendance"] = df["Attendance"].fillna(df["Attendance"].median())

C:\Users\gaurk\AppData\Local\Temp\ipykernel_31780\3741243426.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Attendance"] = df["Attendance"].fillna(df["Attendance"].median())

In [81]:
df['Attendance'].isnull().sum()

np.int64(0)

##### check same for Maths and Physics

In [83]:
print(df.loc[~df["Maths"].between(0, 100), "Maths"])
print(df.loc[~df["Physics"].between(0, 100), "Physics"])

Series([], Name: Maths, dtype: int64)
Series([], Name: Physics, dtype: float64)

In [84]:
df[["Age", "Maths", "Physics", "Attendance"]].describe()

             Age      Maths    Physics  Attendance
count  11.000000  11.000000  11.000000   11.000000
mean   21.636364  80.272727  81.818182   87.090909
std     1.361817  10.238075   9.217572    6.410219
min    19.000000  64.000000  68.000000   76.000000
25%    21.000000  72.500000  76.000000   83.000000
50%    22.000000  82.000000  80.000000   88.000000
75%    22.000000  88.500000  90.500000   91.000000
max    24.000000  95.000000  95.000000   97.000000

In [92]:
print(df["Email"])
print("\n",df["Email"].duplicated().sum())

0     akshat@email.com
1      rahul@email.com
2      priya@email.com
3      arjun@email.com
4       neha@email.com
5      rohan@email.com
6      sneha@email.com
7     vikram@email.com
8              Unknown
10     karan@email.com
11     meera@email.com
Name: Email, dtype: object

 0

In [95]:
print(df.info())
print('\n',df.isnull().sum())

<class 'pandas.core.frame.DataFrame'>
Index: 11 entries, 0 to 11
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        11 non-null     object
 1   Age         11 non-null     float64
 2   Gender      11 non-null     object
 3   City        11 non-null     object
 4   Maths       11 non-null     int64
 5   Physics     11 non-null     float64
 6   Attendance  11 non-null     float64
 7   Email       11 non-null     object
dtypes: float64(3), int64(1), object(4)
memory usage: 1.1+ KB
None

 Name          0
Age           0
Gender        0
City          0
Maths         0
Physics       0
Attendance    0
Email         0
dtype: int64

#### Saving the clean dataset

In [96]:
df.to_csv("Students_cleaned.csv", index=False)